all:
  children:
    aws:
      hosts:
        16.16.182.204:
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /mnt/c/Users/vitbo/.ssh/vitbor-ubuntu.pem
          ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
