# ./playbook/main.yml
---
- name: Main Playbook for Deploying MicroK8s
  hosts: ec2_instances
  become: true
  tasks:
    - name: Include MicroK8s Installation Playbook
      include_tasks: microk8s-install.yml