- name: Įdiegti MicroK8s į EC2
  hosts: microk8s
  become: true

  pre_tasks:
    - name: Palaukti kol SSH taps pasiekiamas
      wait_for:
        port: 22
        host: "{{ ansible_host }}"
        timeout: 300
        state: started
        delay: 10

  roles:
    - microk8s-install
