- name: Set KUBECONFIG env path as fact
  set_fact:
    flux_kubeconfig_path: /home/ubuntu/.kube/config
    
- name: Ensure Helm repo for podinfo exists
  become: true
  environment:
    KUBECONFIG: "{{ flux_kubeconfig_path }}"
  shell: |
    helm repo list | grep -q "^podinfo" || helm repo add podinfo https://stefanprodan.github.io/podinfo
  args:
    warn: false

- name: Update Helm repos
  become: true
  environment:
    KUBECONFIG: "{{ flux_kubeconfig_path }}"
  command: helm repo update

- name: Template podinfo values file
  become: true
  template:
    src: podinfo.yaml.j2
    dest: /tmp/podinfo-values.yaml
  vars:
    podinfo_host: "{{ domain }}"

- name: Deploy podinfo with Helm
  become: true
  environment:
    KUBECONFIG: "{{ flux_kubeconfig_path }}"
  command:
    argv:
      - helm
      - upgrade
      - --install
      - podinfo
      - podinfo/podinfo
      - --namespace
      - podinfo
      - --create-namespace
      - --values
      - /tmp/podinfo-values.yaml

